dist: xenial
services:
  - xvfb

language: python
python:
  - "3.6"
install:
  - pip install tox travis-tox coveralls

# Only turn on the "push branch build" on master
# PRs are enabled by "push PR" setting.
branches:
  only:
  - master

# command to run tests
script:
    - tox
after_success:
    - coveralls
notifications:
    email: false
