name: py35
dependencies:
- scipy>=0.17
- numpy>=1.10
- matplotlib>=1.4
- pip=8.1.1=py35_0
- python=3.5.1=0
- readline=6.2=2
- setuptools=20.3=py35_0
- wheel=0.29.0=py35_0
- pip:
  - momoko>=2.2.3
  - psycopg2>=2.6.1
  - tornado>=4.1
